name: "Clang format checker"
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  clang-format:
    name: "uniqt format checker"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
        with:
            set-safe-directory: true
            
      - name: "Add safe directory"
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        
      - name: "Install colordiff"
        run: sudo apt-get install -y --no-install-recommends colordiff
        
      - name: "Clang format apply"
        uses: diegoferigo/gh-action-clang-format@main
        id: format
        with:
          style: file
          
      - name: "Format result diff"
        if: failure()
        run: printf "${{ steps.format.outputs.diff }}" | colordiff
          
