name: "Clang format checker"
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  clang-format:
    name: "uniqt format checker"
    runs-on: ubuntu-latest
    steps:
      - name: "🔍️ Inspect Environment"
        run: |
          env | grep ^GITHUB
          echo ""
          cat ${GITHUB_EVENT_PATH}
          echo ""
          env

      - name: "Checkout code"
        uses: actions/checkout@v3
        
      - name: "Install colordiff"
        run: sudo apt-get install -y --no-install-recommends colordiff
        
      - name: "Clang format apply"
        uses: diegoferigo/gh-action-clang-format@main
        id: format
        with:
          style: file
          
      - name: "Format result diff"
        if: failure()
        run: printf "${{ steps.format.outputs.diff }}" | colordiff
          
