name: Clang format checker
on: [push]
jobs:
  format:
    name: Format checker
    runs-on: ubuntu-latest
    container: yaishenka/docker-codestyle-checker
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add safe directory
        run: |
            git config --global --add safe.directory /__w/uniqt/uniqt

      - name: Clang format apply step 1
        run: |
            git fetch
            
      - name: Clang format apply step 2.1
        run: |
            git diff -U0 --no-color main
           
      - name: Clang format apply step 2.2
        run: |
            clang-format-diff -p1 -style file | tee format.diff
            
      - name: Clang format apply step 2.3
        run: |
            tee format.diff
           
      - name: Clang format apply step 3
        run: |
            if [ -s format.diff ]; then exit 1; fi
            
      - name: Git status
        run: |
            git status
            
      - name: Upload format
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: format.diff
          path: format.diff
