name: Clang format checker
on: [push]
jobs:
  format:
    name: Format checker
    runs-on: ubuntu-latest
    container: yaishenka/docker-codestyle-checker
    steps:
      - uses: actions/checkout@v3
      - name: Clang format apply
        run: |
            git fetch
            git diff -U0 --no-color origin/main | clang-format-diff -p1 -style file | tee format.diff
            if [ -s format.diff ]; then exit 1; fi
      - name: Upload format
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: format.diff
          path: format.diff
          